name: Docker Build Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu bilgisayardan çek
      uses: actions/checkout@v3

    - name: Docker İmajını İnşa Et
      run: |
        docker build -t cihan-web-app .
        echo "İmaj başarıyla build edildi!"

    - name: Konteyneri Test Et
      run: |
        docker run -d --name test-container cihan-web-app
        sleep 5
        docker ps | grep cihan-web-app
        echo "Konteyner başarıyla ayağa kalktı!"
