services:
  # Mavi SÃ¼rÃ¼m (Mevcut CanlÄ±) ğŸ”µ
  web-app-blue:
    image: ${DOCKERHUB_USERNAME}/devops_project:latest
    ports:
      - "8081:5000"
    environment:
      - REDIS_HOST=redis-server
    depends_on:
      - redis-server

  # YeÅŸil SÃ¼rÃ¼m (Yeni Gelecek) ğŸŸ¢
  web-app-green:
    image: ${DOCKERHUB_USERNAME}/devops_project:${GITHUB_RUN_NUMBER}
    ports:
      - "8082:5000"
    environment:
      - REDIS_HOST=redis-server
    depends_on:
      - redis-server

  # Trafik Polisi ğŸ‘®â€â™‚ï¸
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-app-blue
      - web-app-green

  # VeritabanÄ± ğŸ—„ï¸
  redis-server:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

# Verilerin kalÄ±cÄ± olmasÄ± iÃ§in global volume tanÄ±mÄ±
volumes:
  redis_data:
