services:
  web-app-blue:
    image: ${DOCKERHUB_USERNAME}/devops_project:latest
    ports:
      - "____:5000" # Mavi kapÄ± ðŸ”µ
    environment:
      - REDIS_HOST=redis-server
    depends_on:
      - redis-server

  web-app-green:
    image: ${DOCKERHUB_USERNAME}/devops_project:${GITHUB_RUN_NUMBER}
    ports:
      - "____:5000" # YeÅŸil kapÄ± ðŸŸ¢
    environment:
      - REDIS_HOST=redis-server
    depends_on:
      - redis-server
