name: DevOps & Cloud CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4

      - name: Docker Hub'a Login Ol
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker İmajını İnşa Et ve Pushla
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4

      # Kritik Dosyaları (docker-compose ve nginx.conf) Sunucuya Gönder
      - name: Dosyaları Sunucuya Gönder (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          # Hem docker-compose hem de nginx.conf dosyasını gönderiyoruz
          source: "docker-compose.yml,nginx.conf"
          target: "/root/devops_project"

      - name: Sunucuya SSH ile Bağlan ve Güncelle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: GITHUB_RUN_NUMBER,DOCKERHUB_USERNAME
          script: |
            cd /root/devops_project
            
            # Eğer Docker daha önce yanlışlıkla nginx.conf klasörü oluşturduysa onu sil
            if [ -d "nginx.conf" ]; then rm -rf nginx.conf; fi
            
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            export GITHUB_RUN_NUMBER=${{ github.run_number }}
            
            docker compose pull
            docker compose up -d --force-recreate
