name: DevOps & Cloud CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. ADIM: Docker İmajını İnşa Etme ve Docker Hub'a Gönderme
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4

      - name: Docker Hub'a Login Ol
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker İmajını İnşa Et ve Pushla
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:${{ github.run_number }}

  # 2. ADIM: Sunucuya Dağıtım (Deploy)
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4

      # docker-compose.yml dosyasını sunucuya kopyalar
      - name: Docker Compose Dosyasını Sunucuya Gönder (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/root/devops_project"

      # Sunucuya bağlanıp konteynerları günceller
      - name: Sunucuya SSH ile Bağlan ve Güncelle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Proje klasörüne git
            cd /root/devops_project
            
            # Docker Hub kullanıcı adını değişken olarak tanımla
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            
            # En yeni imajı çek
            docker compose pull
            
            # Sistemi arka planda yeniden başlat
            docker compose up -d
