name: DevOps & Cloud CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. ADIM: Uygulamayı paketleyip Docker Hub'a gönderiyoruz
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4

      - name: Docker Hub'a Login Ol
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker İmajını Oluştur ve Pushla
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:${{ github.run_number }}

  # 2. ADIM: Sunucuya bağlanıp yeni sürümü yayına alıyoruz
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Sunucuya SSH ile Bağlan ve Güncelle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Proje klasörüne git
            cd /root/devops_project
            
            # Docker Hub kullanıcı adını değişken olarak al
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            
            # En yeni imajları çek
            docker compose pull
            
            # Konteynerları güncelle (arka planda çalıştır)
            docker compose up -d
