name: DevOps & Cloud CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # 1. BÖLÜM: Docker Hub'a Gönderim
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4

      - name: Docker Hub'a Login Ol
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker İmajını İnşa Et ve Pushla
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:${{ github.run_number }}

  # 2. BÖLÜM: Sunucuya Dağıtım (Deploy)
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Sunucuya SSH ile Bağlan ve Güncelle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }} # BURAYA DİKKAT: GitHub'daki isimle aynı olmalı
          script: |
            # Eğer klasör yoksa oluştur
            mkdir -p /root/devops_project
            cd /root/devops_project
            
            # Değişkeni tanımla
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            
            # Yeni imajı çek ve sistemi ayağa kaldır
            docker compose pull
            docker compose up -d
